language: go
sudo: required
dist: trusty

go:
  - 1.10.x
  - 1.11.x

before_script:
  - mysql -u root --password="" < db.sql

script:
  - go get github.com/spf13/viper
  - go get github.com/spf13/pflag
  - go get github.com/lexkong/log
  - go get github.com/gin-gonic/gin
  - go get github.com/jinzhu/gorm
  - go get github.com/jinzhu/gorm/dialects/mysql
  - make test

services:
  - mysql
