runmode: debug
addr: :8083
name: apiserver
url: http://127.0.0.1:8083
max_ping_count: 10
jwt_secret: Rtg8BPKNEf2mB4mgvKONGPZZQSaJWNLijxR42qRgq0iBb5
log:
  writers: file,stdout
  logger_level: DEBUG
  logger_file: log/apiserver.log
  log_format_text: false
  rollingPolicy: size
  log_rotate_date: 1
  log_rotate_size: 1
  log_backup_count: 7
db:
  name: muxisite_auth
  addr: 0.0.0.0:3306
  username: root
  password:
cas:
  server_url: http://localhost:8443/cas
  callback_base_url: http://localhost:8083